version: 2.1

jobs:
  setup:
    docker:
      - image: andreysenov/firebase-tools:13.5.1-node-20
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Save cache
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  lint:
    docker:
      - image: andreysenov/firebase-tools:13.5.1-node-20
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run lint
  build_and_deploy:
    docker:
      - image: andreysenov/firebase-tools:13.5.1-node-20
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Make keys file
          command: echo ${FOOD_KEYS} > keys.json
      - run:
          name: Deploy to Firebase Hosting
          command: firebase deploy --only hosting
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: "keys.json"


workflows:
  lint_build_test:
    jobs:
      - setup:
          filters:
            branches:
              only: main
      - lint:
          filters:
            branches:
              only: main
          requires:
            - setup
      - build:
          filters:
            branches:
              only: main
          requires:
            - lint
